# Generated by Django 4.2.5 on 2023-10-02 14:25

import app.form.file_with_img_preview
import app.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('exportBaseUrl', models.URLField(verbose_name='Export Base-URL')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(default=app.utils.random_secret, editable=False, max_length=20)),
                ('member_id', models.CharField(max_length=20, verbose_name='Mitglieder-Nr.')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('valid_since', models.DateField(verbose_name='Mitglied seit')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Mitglied bis')),
                ('image', app.form.file_with_img_preview.FileWithImagePreview(blank=True, help_text='Ideal: 250 x 320 px (JPEG oder PNG)', null=True, upload_to=app.utils.overwrite_upload, validators=[app.form.file_with_img_preview.ImageValidator.validate], verbose_name='Bild')),
                ('additional', models.JSONField(blank=True, null=True, verbose_name='Zusätzliche Daten (JSON)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.organization')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
            },
        ),
    ]
